/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sicar.reporteador;


import com.sicar.reporteador.comp.NumeroLinea;
import java.io.IOException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class PReporteador extends javax.swing.JPanel {
    
    private ReporteadorService service;
    public TableModel modelo;
    public String consultaEditor;
    public JTextField text;
    
    public PReporteador() {
        initComponents();
        
        tabla.getTableHeader();
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        scrollEditor.setRowHeaderView(new NumeroLinea(editor));
        scrollEditor.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollEditor.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        text = new JTextField();
        text.setBorder(null);
        Comando cm = new Comando();
        cm.ctrlEnter(editor, tabla, labelStatus, labelResult,LTotal);
        modelo = new DefaultTableModel();
        tabla.setModel(modelo);
        
        consultaEditor = editor.getText();
        //pasar.openDialog(BSumarVarias);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tabPane = new javax.swing.JTabbedPane();
        scrollPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buttonGenerar = new javax.swing.JButton();
        BExportar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bGraficar = new javax.swing.JButton();
        scrollEditor = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelResult = new javax.swing.JLabel();
        LTotal = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setColumnSelectionAllowed(true);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tabla);
        tabla.getAccessibleContext().setAccessibleName("");

        tabPane.addTab("Resultados", scrollPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(tabPane, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(2, 114, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(767, 55));

        buttonGenerar.setBackground(new java.awt.Color(0, 153, 0));
        buttonGenerar.setForeground(new java.awt.Color(255, 255, 255));
        buttonGenerar.setText("Generar");
        buttonGenerar.setMaximumSize(new java.awt.Dimension(120, 37));
        buttonGenerar.setMinimumSize(new java.awt.Dimension(100, 25));
        buttonGenerar.setPreferredSize(new java.awt.Dimension(135, 25));
        buttonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarActionPerformed(evt);
            }
        });

        BExportar.setText("Exportar");
        BExportar.setPreferredSize(new java.awt.Dimension(135, 25));
        BExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExportarActionPerformed(evt);
            }
        });

        jButton2.setText("Descargar");
        jButton2.setPreferredSize(new java.awt.Dimension(135, 25));

        bGraficar.setText("Graficar");
        bGraficar.setPreferredSize(new java.awt.Dimension(135, 25));
        bGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BExportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGraficar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        scrollEditor.setMinimumSize(new java.awt.Dimension(25, 100));
        scrollEditor.setPreferredSize(new java.awt.Dimension(100, 250));

        editor.setColumns(20);
        editor.setRows(5);
        editor.setText("SELECT * FROM venta");
        scrollEditor.setViewportView(editor);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(scrollEditor, gridBagConstraints);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelStatus.setText("Hola :)");
        jPanel2.add(labelStatus);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel2.add(jPanel3);

        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelResult.setText("Resultados:");
        jPanel2.add(labelResult);

        LTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LTotal.setText("Total:");
        jPanel2.add(LTotal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    private void buttonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarActionPerformed
        
        if (service == null) {
            service = new ReporteadorService();
            if (service.connect("Localhost", "sicar", "root", "testprueba") == 1) {
            } else {
                JOptionPane.showMessageDialog(this, "No Conectado a la BD");
                System.exit(0);
            }
        }
        long init = System.currentTimeMillis();
        service.build(editor.getText(), tabla);
        EliminarColumnas ec = new EliminarColumnas();
        ec.eliminarColumnas_Id(tabla);
        ec.eliminarColumnasNulas(tabla);
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            if (tabla.getColumnName(i).equalsIgnoreCase("Total")) {
                Total tl = new Total();
                tl.ObtenerTotal(tabla,LTotal);
            }
        }
        
        labelStatus.setText("Terminado en " + (System.currentTimeMillis() - init) + " ms");
        for (int i = 0; i < tabla.getRowCount(); i++) {
            labelResult.setText("Resultados " + (i + 1));
        }
    }//GEN-LAST:event_buttonGenerarActionPerformed

    private void bGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGraficarActionPerformed
        Graficador.graficar(tabla, tabPane);
    }//GEN-LAST:event_bGraficarActionPerformed

    private void BExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExportarActionPerformed
        Exporter obj;
        try {
            obj = new Exporter();
            obj.exportarExcel(tabla);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_BExportarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExportar;
    private javax.swing.JLabel LTotal;
    private javax.swing.JButton bGraficar;
    private javax.swing.JButton buttonGenerar;
    private javax.swing.JTextArea editor;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JScrollPane scrollEditor;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
